//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlnt.DB.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietKH
    {
        public int MaKH { get; set; }
        public int MaLoai { get; set; }
        public bool HoanThanh { get; set; }
    
        public virtual KeHoach KeHoach { get; set; }
        public virtual LoaiKH LoaiKH { get; set; }
    }
}
