//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlnt.DB.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietXuat_TBV
    {
        public int MaPhieuXuat { get; set; }
        public int MaThuoc { get; set; }
        public double SoLuong { get; set; }
    
        public virtual PhieuXuat PhieuXuat { get; set; }
        public virtual ThuocBaoVeTV ThuocBaoVeTV { get; set; }
    }
}
