//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlnt.DB.Entity
{
    using System;
    
    public partial class getListNongSan_Result1
    {
        public string TenNS { get; set; }
        public Nullable<System.DateTime> HaSD { get; set; }
        public int MaLoaiCay { get; set; }
        public double SanLuong { get; set; }
    }
}
