//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlnt.DB.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeHoach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KeHoach()
        {
            this.ChiTietKH = new HashSet<ChiTietKH>();
        }
    
        public int MaKeHoach { get; set; }
        public string NoiDung { get; set; }
        public System.DateTime NgayThucHien { get; set; }
        public int SoLuongCongViec { get; set; }
        public int SoLuongCongViecHoanThanh { get; set; }
        public string ChuThich { get; set; }
        public int MaNguoiLap { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietKH> ChiTietKH { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
