//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlnt.DB.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanBon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhanBon()
        {
            this.ChiTietNhap_PB = new HashSet<ChiTietNhap_PB>();
            this.ChiTietXuat_PB = new HashSet<ChiTietXuat_PB>();
        }
    
        public int MaPB { get; set; }
        public string TenPB { get; set; }
        public string Loai { get; set; }
        public double DonGia { get; set; }
        public double KhoiLuong { get; set; }
        public int SoLuong { get; set; }
        public System.DateTime NgaySX { get; set; }
        public System.DateTime HanSD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietNhap_PB> ChiTietNhap_PB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietXuat_PB> ChiTietXuat_PB { get; set; }
    }
}
