//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlnt.DB.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLNTEntities1 : DbContext
    {
        public QLNTEntities1()
            : base("name=QLNTEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BangThuHoach> BangThuHoach { get; set; }
        public virtual DbSet<Cay> Cay { get; set; }
        public virtual DbSet<ChiTiet_TH> ChiTiet_TH { get; set; }
        public virtual DbSet<ChiTietHoaDon> ChiTietHoaDon { get; set; }
        public virtual DbSet<ChiTietKH> ChiTietKH { get; set; }
        public virtual DbSet<ChiTietNhap_PB> ChiTietNhap_PB { get; set; }
        public virtual DbSet<ChiTietNhap_TBV> ChiTietNhap_TBV { get; set; }
        public virtual DbSet<ChiTietXuat_PB> ChiTietXuat_PB { get; set; }
        public virtual DbSet<ChiTietXuat_TBV> ChiTietXuat_TBV { get; set; }
        public virtual DbSet<DoDoc> DoDoc { get; set; }
        public virtual DbSet<HoaDon> HoaDon { get; set; }
        public virtual DbSet<KeHoach> KeHoach { get; set; }
        public virtual DbSet<KhachHang> KhachHang { get; set; }
        public virtual DbSet<LoaiKH> LoaiKH { get; set; }
        public virtual DbSet<NhaCungCap> NhaCungCap { get; set; }
        public virtual DbSet<NhanVien> NhanVien { get; set; }
        public virtual DbSet<NongSan> NongSan { get; set; }
        public virtual DbSet<PhanBon> PhanBon { get; set; }
        public virtual DbSet<PhieuNhap> PhieuNhap { get; set; }
        public virtual DbSet<PhieuXuat> PhieuXuat { get; set; }
        public virtual DbSet<Quyen> Quyen { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<ThuocBaoVeTV> ThuocBaoVeTV { get; set; }
    
        public virtual ObjectResult<getListNongSan_Result4> getListNongSan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getListNongSan_Result4>("getListNongSan");
        }
    
        public virtual ObjectResult<ThongKeDoanhThuTheoNam_Result1> ThongKeDoanhThuTheoNam(Nullable<int> y)
        {
            var yParameter = y.HasValue ?
                new ObjectParameter("y", y) :
                new ObjectParameter("y", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ThongKeDoanhThuTheoNam_Result1>("ThongKeDoanhThuTheoNam", yParameter);
        }
    
        public virtual ObjectResult<ThongKeSanLuong_Result1> ThongKeSanLuong(Nullable<int> m, Nullable<int> y)
        {
            var mParameter = m.HasValue ?
                new ObjectParameter("m", m) :
                new ObjectParameter("m", typeof(int));
    
            var yParameter = y.HasValue ?
                new ObjectParameter("y", y) :
                new ObjectParameter("y", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ThongKeSanLuong_Result1>("ThongKeSanLuong", mParameter, yParameter);
        }
    }
}
