//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlnt.DB.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThuocBaoVeTV
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThuocBaoVeTV()
        {
            this.ChiTietNhap_TBV = new HashSet<ChiTietNhap_TBV>();
            this.ChiTietXuat_TBV = new HashSet<ChiTietXuat_TBV>();
        }
    
        public int MaThuoc { get; set; }
        public string TenThuoc { get; set; }
        public int ThoiGianCachLy { get; set; }
        public string NoiSX { get; set; }
        public string Dang { get; set; }
        public int SoLuong { get; set; }
        public string CongDung { get; set; }
        public System.DateTime NgaySX { get; set; }
        public System.DateTime HanSD { get; set; }
        public string MaDoc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietNhap_TBV> ChiTietNhap_TBV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietXuat_TBV> ChiTietXuat_TBV { get; set; }
        public virtual DoDoc DoDoc { get; set; }
    }
}
